import VARIABLES from './variables';

export default {
  HOTKEYS: {
    ITEMS: [
      VARIABLES.HOTKEYS.DISABLE,
      VARIABLES.HOTKEYS.START,
      VARIABLES.HOTKEYS.STOP,
      VARIABLES.HOTKEYS.NEXT,
      VARIABLES.HOTKEYS.PREV,
      VARIABLES.HOTKEYS.PLAY,
    ],
  },
  SETTINGS: {
    ITEMS: [
      VARIABLES.SETTINGS.VOLUME,
      VARIABLES.SETTINGS.PITCH,
      VARIABLES.SETTINGS.RATE,
      VARIABLES.SETTINGS.VOICE,
    ],
  },
  APP: {
    ITEMS: [
      VARIABLES.APP.AUTOSCROLL,
      VARIABLES.APP.HIGHLIGHT_COLOR,
      VARIABLES.APP.HIGHLIGHT_STYLE,
      VARIABLES.APP.LANGUAGE,
      VARIABLES.APP.CREDITS,
      VARIABLES.APP.CREDITS_RESET_TIMER,
      VARIABLES.APP.SERVICE_REGION,
      VARIABLES.APP.SERVICE_KEY,
      VARIABLES.APP.SKIP_DEAD_SECTIONS,
      VARIABLES.APP.WORD_TRACKER,
      VARIABLES.APP.WORD_TRACKER_COLOR,
      VARIABLES.APP.WORD_TRACKER_STYLE,
      VARIABLES.APP.SECTION_TRACKER,
      VARIABLES.APP.THEME_MODE,
      VARIABLES.APP.MINI_PLAYER,
    ],
  },
};
