import { createActions, } from 'redux-actions';

export default createActions({
  PLAYER: {
    SET: null,
    PLAY: null,
    PROXY_PLAY: null,
    START: null,
    READY: null,
    PAUSE: null,
    RESUME: null,
    CONTINUE: null,
    RESUME_EVENT: null,
    RESTART: null,
    DEMAND: null,
    STOP: null,
    SOFT_HALT: null,
    HALT: null,
    SEEK: null,
    NEXT: null,
    NEXT_MOVE: null,
    SOFT_NEXT: null,
    NEXT_AUTO: null,
    NEXT_SLOW: null,
    PREV: null,
    PREV_MOVE: null,
    SOFT_PREV: null,
    PREV_SLOW: null,
    WAIT: null,
    RESET: null,
    WANK: null,
    OVERLOAD: null,
    LOADING: null,
    CHILL: null,
    CRASH: null,
    END: null,
    TIMEOUT: null,
    HEALTH_CHECK: null,
    TOGGLE: null,
    ERROR: null,
  },

  SECTIONS: {
    REQUEST: null,
    REQUEST_AND_PLAY: null,
    REQUEST_AND_PLAY_COMPLETE: null,
    SUCCESS: null,
    FAILURE: null,
    SET: null,
    READ_ELEMENT: null,
  },
});
